version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"


  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_started
        restart: true